trigger : none

resources:
  - repo: self

variables:
  tag: $(Build.BuildId)
  imageRepo: crypto-webapp-repo
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build an image
    pool: default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-connection'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  variables:
    acrsecret: k8sacrauth
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool: default
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifests'
    - task: KubernetesManifest@0
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: 'k8s-connection'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: '$(acrsecret)'
        dockerRegistryEndpoint: 'acr-connection'

    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'k8s-connection'
        namespace: 'default'
        manifests: |
           '$(Pipeline.Workspace)/manifests/deployment.yml'
           '$(Pipeline.Workspace)/manifests/service.yml'
