apiVersion : apps/v1
kind: Deployment
metadata:
  name: cryptoapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cryptoapp
  template:
    metadata:
      labels:
        app: cryptoapp
    spec:
      containers:
        - name: cryptoapp 
          image: registruaks.azurecr.io/repo-crypto-app
          ports:
          - containerPort: 80
