
apiVersion: v1
kind: Pod
metadata:
  name: cryptoapp
  labels:
    app: cryptoapp
spec:
  containers:
  - image: "registruaks.azurecr.io/cryptoapp"
    name: crypto-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: cryptoapp
spec:
  selector:
    app: cryptoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cryptoapp
  annotations:
    kubernetes.io/ingress.class: azure/ingress-appgateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: cryptoapp
            port:
              number: 80
        pathType: Exact
